/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:206abb45-3a3c-4f11-9a3d-2829c152397d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_aXwumkhYZ",
    "aws_user_pools_web_client_id": "1v5i9br9cm66pnpsb2lrsqdgtf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://h4ac7mrbqfgw3mwv4ygcbeulri.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ejaas2gz2zecjlrnqivtbsywke",
    "aws_user_files_s3_bucket": "your-unique-bucket-name235428-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
